version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: rails_jwt_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finance

volumes:
  postgres_data:

networks:
  finance: