
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_jwt_development
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: rails_jwt_test
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  primary: &primary_production
    <<: *default
    database: rails_jwt_production
    username: rails_jwt
    password: <%= ENV["RAILS_JWT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_jwt_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_jwt_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_jwt_production_cable
    migrations_paths: db/cable_migrate
